version: '3.1'
services:
    s3-solr-sync:
        image: s3-solr-synch
        build:
            context: .
            dockerfile: Dockerfile
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                condition: on-failure
        container_name: s3-solr-synch
        environment:
            - NODE_ENV=development
            - PORT=${HTTP_PORT}
        ports:
            - "${HTTP_PORT}:${HTTP_PORT}"
        restart: always
        volumes:
            - /tmp/output/subjects:/opt/output/subjects
            - /tmp/output/terms:/opt/output/terms
            - /tmp/output/places:/opt/output/places
            # MOUNT FILESYSTEMS TO BE WATCHED HERE
            # ADJUST THEIR IN-CONTAINER PATHS IN .env